version: '3.1'
services :
  db:
    image: postgres:10-alpine
    ports:
      - "${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - ${AMINER_PORT}:${AMINER_PORT}